project:
  type: website
  output-dir: docs

website:
  title: "UGC NET Computer Science"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: about.qmd
        text: About

  sidebar:
    style: "docked"
    contents:

      - href: index.qmd
        text: Home

      # =========================
      # UNIT 1
      # =========================

      - section: "Unit 1 – Discrete Structures and Optimization"
        contents:

          - href: unit1.qmd
            text: Overview

          - href: unit1/mathematical-logic.qmd
            text: Mathematical Logic

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true